/* This file is automatically generated by gen_frontend.py */
/* DO NOT EDIT! */

#ifndef _FMMV_3D_H_
#define _FMMV_3D_H_

#define STAT_MAX 20
#define MAX_NUM_PAPI_EVENTS 10

enum StatStep {
        STAT_TOTAL,
        STAT_BUILD_TREE, 
	STAT_GEN_M,
        STAT_M2M, 
	STAT_M2L, 
	STAT_L2L,
        STAT_EVAL_L,
        STAT_LIST1, 
	STAT_LIST3, 
	STAT_LIST4, 
	STAT_LIST34,
        STAT_FARFIELD, 
	STAT_NEARFIELD,
	STAT_INITIALIZE,
	STAT_EVALUATE,
	STAT_FINALIZE,
	_STAT_LAST_ /* mark last entry, do not remove! */	
};

struct FmmvStatistics {
	double time[STAT_MAX];
	double etime[STAT_MAX];

	int PAPIeventSet;
	long long int PAPIvalues[STAT_MAX][MAX_NUM_PAPI_EVENTS];

	int pM;
	int pL;
	int s_eps;
	int s_exp;
		
	int noOfParticles;
	int noOfTargets;
	int noOfSourceLevels;
	int noOfTargetLevels;
	
	int maxNoOfStoredXin;
	int maxAllocatedMemory;
	long long int noOfDirectInteractions;

	int noOfSourceBoxes;
	int noOfTargetBoxes;
	int noOfSourceLeafBoxes;
	int noOfTargetLeafBoxes;
	float averageNoOfParticlesPerLeafBox;
	float averageNoOfTargetsPerLeafBox;

	int noOfParticlesInLevel[52];
	int noOfTargetsInLevel[52];
	int noOfSourceBoxesInLevel[52];
	int noOfTargetBoxesInLevel[52];
	int noOfSourceLeafBoxesInLevel[52];
	int noOfTargetLeafBoxesInLevel[52];
	float averageNoOfParticlesPerLeafBoxInLevel[52];
	float averageNoOfTargetsPerLeafBoxInLevel[52];
	
};

void printFmmvStatistics(struct FmmvStatistics *stat);
	
struct FmmvOptions {
	double beta; /* default: 0 */

	int pM; /* default:6 */
	int pL; /* default:6 */
	int s; 

	int ws; /* default: 1 */
	int reducedScheme;

	double scale; /* default: 1 */
	int splitThreshold;  
	int splitTargetThreshold; 
	int levels;
	int directEvalThreshold;  
	int periodicBoundaryConditions; /* default: 0 */
	int extrinsicCorrection; /* default: 0 */
	int useHilbertOrder;  	/* default: 0, i.e. use Molton order */
	int directEvalAccuracy;	/* default: 2 (double) resp. 1 (single) */
	int useFarfieldNearfieldThreads;	/* default: 0 */
	
	int PAPIeventSet;

	double *x;
	double *w;
	int *M;
};

struct FmmvOptions fmmvGetDefaultOptions(void);
	
void fmmv3df(
	unsigned int NParticles, 
	float particles[][3],
	float charges[],
	float dipoleMoments[][3],
	unsigned int NTargets, 
	float targets[][3],
	float potentials[],
	float gradients[][3],
	struct FmmvOptions *options, /* if NULL use default options */
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);

void fmmv3d(
	unsigned int NParticles, 
	double particles[][3],
	double charges[],
	double dipoleMoments[][3],
	unsigned int NTargets, 
	double targets[][3],
	double potentials[],
	double gradients[][3],
	struct FmmvOptions *options, /* if NULL use default options */
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);

#define DIPOLEMOMENTS 1
#define CHARGES 2

#define POTENTIALS 1
#define GRADIENTS 2

void fmmv3df_initialize(
	void** fmmvHandle,
	unsigned int NParticles,
	float particles[][3],
	int typeSources,
	unsigned int NTargets, 
	float targets[][3],
	int typeTargets,
	struct FmmvOptions *options, /* if NULL use default options */
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);

void fmmv3d_initialize(
	void** fmmvHandle,
	unsigned int NParticles,
	double particles[][3],
	int typeSources,
	unsigned int NTargets, 
	double targets[][3],
	int typeTargets,
	struct FmmvOptions *options, /* if NULL use default options */
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);

void fmmv3df_evaluate(
	void* fmmvHandle,
	float charges[],
	float dipoleMoments[][3],
	float potentials[],
	float gradients[][3],
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);

void fmmv3d_evaluate(
	void* fmmvHandle,
	double charges[],
	double dipoleMoments[][3],
	double potentials[],
	double gradients[][3],
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);

void fmmv3df_finalize(
	void* fmmvHandle,
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);

void fmmv3d_finalize(
	void* fmmvHandle,
	struct FmmvStatistics *statistics, /* can be NULL */
	char **errorMessage);


void fmmv3df_direct(
	unsigned int NParticles, 
	float particles[][3],
	float charges[],
	float dipoleMoments[][3],
	unsigned int NTargets, 
	float targets[][3],
	float potentials[],
	float gradients[][3],
	int accuracy,
	double beta,
	double *time,
	char **errorMessage);

void fmmv3d_direct(
	unsigned int NParticles, 
	double particles[][3],
	double charges[],
	double dipoleMoments[][3],
	unsigned int NTargets, 
	double targets[][3],
	double potentials[],
	double gradients[][3],
	int accuracy,
	double beta,
	double *time,
	char **errorMessage);

#endif /* _FMMV_3D_H_ */
