/*
! +-----------------------------------------------+
! |        Generated by SPL Compiler 3.30         |
! +-----------------------------------------------+
! Command-line options: -l -B 32 -C -xprecision=double -xposw -xsubname=FFT_M2X_2 
! 
*/
/*
! The SPL Program: (F 2)
! node size: 2 X 2
*/


	void FFT_M2X_2(double *y, double *x) {

	  y[2] = x[0] - x[2];
	  y[3] = x[1] - x[3];
	  y[0] = x[0] + x[2];
	  y[1] = x[1] + x[3];


	}
	void init_FFT_M2X_2( void )
	{
	}

