/*
! +-----------------------------------------------+
! |        Generated by SPL Compiler 3.30         |
! +-----------------------------------------------+
! Command-line options: -l -B 32 -C -xprecision=double -xposw -xsubname=FFT_M2X_4 
! 
*/
/*
! The SPL Program: (compose (direct_sum (I 1)(conjugate (..)(..)))(compose (direct_sum (..)(..))(direct_sum (..)(..))))
! node size: 4 X 4
*/


	void FFT_M2X_4(double *y, double *x) {
	double f0;
	double f1;
	double f2;
	double f3;
	double f4;
	double f5;
	double f6;
	double f7;

	  f0 = x[2] - x[6];
	  f1 = x[3] - x[7];
	  f2 = x[2] + x[6];
	  f3 = x[3] + x[7];
	  f4 = x[0] - x[4];
	  f5 = x[1] - x[5];
	  f6 = x[0] + x[4];
	  f7 = x[1] + x[5];
	  y[4] = f6 - f2;
	  y[5] = f7 - f3;
	  y[0] = f6 + f2;
	  y[1] = f7 + f3;
	  y[6] = f4 + f1;
	  y[7] = f5 - f0;
	  y[2] = f4 - f1;
	  y[3] = f5 + f0;


	}
	void init_FFT_M2X_4( void )
	{
	}

