/*
! +-----------------------------------------------+
! |        Generated by SPL Compiler 3.30         |
! +-----------------------------------------------+
! Command-line options: -l -B 32 -C -xprecision=double -xposw -xsubname=FFT_X2L_12 
! 
*/
/*
! The SPL Program: (compose (permutation (...1 x 12 ...))(compose (permutation (...1 x 12 ...))(compose (..)(..))))
! node size: 12 X 12
*/


	void FFT_X2L_12(double *y, double *x) {
	double f0;
	double f1;
	double f2;
	double f3;
	double f4;
	double f5;
	double f6;
	double f7;
	double f8;
	double f9;
	double f10;
	double f11;
	double f12;
	double f13;
	double f14;
	double f15;
	double f16;
	double f17;
	double f18;
	double f19;
	double f20;
	double f21;
	double f22;
	double f23;
	double f24;
	double f25;
	double f26;
	double f27;
	double f28;
	double f29;
	double f30;
	double f31;
	double f32;
	double f33;
	double f34;
	double f35;
	double f36;
	double f37;
	double f38;
	double f39;
	double f40;
	double f41;
	double f42;
	double f43;
	double f44;
	double f45;
	double f46;
	double f47;
	double f48;
	double f49;
	double f50;
	double f51;
	double f54;
	double f55;
	double f56;
	double f57;
	double f58;
	double f59;
	double f64;
	double f65;
	double f66;
	double f67;
	double f70;
	double f71;
	double f72;
	double f73;
	double f74;
	double f75;
	double f80;
	double f81;
	double f82;
	double f83;
	double f86;
	double f87;
	double f88;
	double f89;
	double f90;
	double f91;
	double f96;
	double f97;
	double f98;
	double f99;
	double f102;
	double f103;
	double f104;
	double f105;
	double f106;
	double f107;

	  f0 = x[18] - x[6];
	  f1 = x[19] - x[7];
	  f2 = x[18] + x[6];
	  f3 = x[19] + x[7];
	  f4 = x[0] - x[12];
	  f5 = x[1] - x[13];
	  f6 = x[0] + x[12];
	  f7 = x[1] + x[13];
	  f8 = f6 - f2;
	  f9 = f7 - f3;
	  f10 = f6 + f2;
	  f11 = f7 + f3;
	  f12 = f4 + f1;
	  f13 = f5 - f0;
	  f14 = f4 - f1;
	  f15 = f5 + f0;
	  f16 = x[2] - x[14];
	  f17 = x[3] - x[15];
	  f18 = x[2] + x[14];
	  f19 = x[3] + x[15];
	  f20 = x[8] - x[20];
	  f21 = x[9] - x[21];
	  f22 = x[8] + x[20];
	  f23 = x[9] + x[21];
	  f24 = f22 - f18;
	  f25 = f23 - f19;
	  f26 = f22 + f18;
	  f27 = f23 + f19;
	  f28 = f20 + f17;
	  f29 = f21 - f16;
	  f30 = f20 - f17;
	  f31 = f21 + f16;
	  f32 = x[10] - x[22];
	  f33 = x[11] - x[23];
	  f34 = x[10] + x[22];
	  f35 = x[11] + x[23];
	  f36 = x[16] - x[4];
	  f37 = x[17] - x[5];
	  f38 = x[16] + x[4];
	  f39 = x[17] + x[5];
	  f40 = f38 - f34;
	  f41 = f39 - f35;
	  f42 = f38 + f34;
	  f43 = f39 + f35;
	  f44 = f36 + f33;
	  f45 = f37 - f32;
	  f46 = f36 - f33;
	  f47 = f37 + f32;
	  f48 = f26 - f42;
	  f49 = f27 - f43;
	  f50 = f26 + f42;
	  f51 = f27 + f43;
	  y[0] = f10 + f50;
	  y[1] = f11 + f51;
	  f54 = 5.0000000000000000e-01 * f50;
	  f55 = 5.0000000000000000e-01 * f51;
	  f56 = f10 - f54;
	  f57 = f11 - f55;
	  f58 = 8.6602540378443860e-01 * f49;
	  f59 = 8.6602540378443860e-01 * f48;
	  y[8] = f56 + f58;
	  y[9] = f57 - f59;
	  y[16] = f56 - f58;
	  y[17] = f57 + f59;
	  f64 = f30 - f46;
	  f65 = f31 - f47;
	  f66 = f30 + f46;
	  f67 = f31 + f47;
	  y[18] = f14 + f66;
	  y[19] = f15 + f67;
	  f70 = 5.0000000000000000e-01 * f66;
	  f71 = 5.0000000000000000e-01 * f67;
	  f72 = f14 - f70;
	  f73 = f15 - f71;
	  f74 = 8.6602540378443860e-01 * f65;
	  f75 = 8.6602540378443860e-01 * f64;
	  y[2] = f72 + f74;
	  y[3] = f73 - f75;
	  y[10] = f72 - f74;
	  y[11] = f73 + f75;
	  f80 = f24 - f40;
	  f81 = f25 - f41;
	  f82 = f24 + f40;
	  f83 = f25 + f41;
	  y[12] = f8 + f82;
	  y[13] = f9 + f83;
	  f86 = 5.0000000000000000e-01 * f82;
	  f87 = 5.0000000000000000e-01 * f83;
	  f88 = f8 - f86;
	  f89 = f9 - f87;
	  f90 = 8.6602540378443860e-01 * f81;
	  f91 = 8.6602540378443860e-01 * f80;
	  y[20] = f88 + f90;
	  y[21] = f89 - f91;
	  y[4] = f88 - f90;
	  y[5] = f89 + f91;
	  f96 = f28 - f44;
	  f97 = f29 - f45;
	  f98 = f28 + f44;
	  f99 = f29 + f45;
	  y[6] = f12 + f98;
	  y[7] = f13 + f99;
	  f102 = 5.0000000000000000e-01 * f98;
	  f103 = 5.0000000000000000e-01 * f99;
	  f104 = f12 - f102;
	  f105 = f13 - f103;
	  f106 = 8.6602540378443860e-01 * f97;
	  f107 = 8.6602540378443860e-01 * f96;
	  y[14] = f104 + f106;
	  y[15] = f105 - f107;
	  y[22] = f104 - f106;
	  y[23] = f105 + f107;


	}
	void init_FFT_X2L_12( void )
	{
	}

