/*
! +-----------------------------------------------+
! |        Generated by SPL Compiler 3.30         |
! +-----------------------------------------------+
! Command-line options: -l -B 32 -C -xprecision=double -xposw -xsubname=FFT_M2X_36 
! 
*/
/*
! The SPL Program: (compose (permutation (...1 x 36 ...))(compose (tensor (..)(..))(compose (..)(..))))
! node size: 36 X 36
*/


	void FFT_M2X_36(double *y, double *x) {
	int i0;
	double f0;
	double f1;
	double f2;
	double f3;
	double f4;
	double f5;
	double f6;
	double f7;
	double f8;
	double f9;
	double f10;
	double f11;
	double f12;
	double f13;
	double f14;
	double f15;
	double f16;
	double f17;
	double f18;
	double f19;
	double f20;
	double f21;
	double f22;
	double f23;
	double f24;
	double f25;
	double f26;
	double f27;
	double f28;
	double f29;
	double f30;
	double f31;
	double f44;
	double f45;
	double f46;
	double f47;
	double f50;
	double f51;
	double f52;
	double f53;
	double f54;
	double f55;
	double f56;
	double f57;
	double f58;
	double f59;
	double f60;
	double f61;
	double f62;
	double f63;
	double f64;
	double f65;
	double f66;
	double f67;
	double f68;
	double f69;
	double f70;
	double f71;
	double f72;
	double f73;
	double f74;
	double f75;
	double f76;
	double f77;
	double f78;
	double f79;
	double f80;
	double f81;
	  static double t18[72];
	  static double t19[72];
	  static double t20[72];
	  extern double T_36_6 [72];

	  /* deftemp t18 ( 72 ) */
	  /* deftemp t19 ( 72 ) */
	  /* deftemp t20 ( 72 ) */
	  for (i0 = 0; i0 < 6; i0++) {  
	    f0 = x[2*i0+48] - x[2*i0+24];
	    f1 = x[2*i0+49] - x[2*i0+25];
	    f2 = x[2*i0+48] + x[2*i0+24];
	    f3 = x[2*i0+49] + x[2*i0+25];
	    f4 = x[2*i0] + f2;
	    f5 = x[2*i0+1] + f3;
	    f6 = 5.0000000000000000e-01 * f2;
	    f7 = 5.0000000000000000e-01 * f3;
	    f8 = x[2*i0] - f6;
	    f9 = x[2*i0+1] - f7;
	    f10 = 8.6602540378443860e-01 * f1;
	    f11 = 8.6602540378443860e-01 * f0;
	    f12 = f8 + f10;
	    f13 = f9 - f11;
	    f14 = f8 - f10;
	    f15 = f9 + f11;
	    f16 = x[2*i0+12] - x[2*i0+60];
	    f17 = x[2*i0+13] - x[2*i0+61];
	    f18 = x[2*i0+12] + x[2*i0+60];
	    f19 = x[2*i0+13] + x[2*i0+61];
	    f20 = x[2*i0+36] + f18;
	    f21 = x[2*i0+37] + f19;
	    f22 = 5.0000000000000000e-01 * f18;
	    f23 = 5.0000000000000000e-01 * f19;
	    f24 = x[2*i0+36] - f22;
	    f25 = x[2*i0+37] - f23;
	    f26 = 8.6602540378443860e-01 * f17;
	    f27 = 8.6602540378443860e-01 * f16;
	    f28 = f24 + f26;
	    f29 = f25 - f27;
	    f30 = f24 - f26;
	    f31 = f25 + f27;
	    t20[2*i0+36] = f4 - f20;
	    t20[2*i0+37] = f5 - f21;
	    t20[2*i0] = f4 + f20;
	    t20[2*i0+1] = f5 + f21;
	    t20[2*i0+60] = f14 - f30;
	    t20[2*i0+61] = f15 - f31;
	    t20[2*i0+24] = f14 + f30;
	    t20[2*i0+25] = f15 + f31;
	    t20[2*i0+12] = f12 - f28;
	    t20[2*i0+13] = f13 - f29;
	    t20[2*i0+48] = f12 + f28;
	    t20[2*i0+49] = f13 + f29;
	    }
	  for (i0 = 0; i0 < 36; i0++) {  
	    f44 = T_36_6[2*i0] * t20[2*i0];
	    f45 = T_36_6[2*i0+1] * t20[2*i0+1];
	    f46 = T_36_6[2*i0] * t20[2*i0+1];
	    f47 = T_36_6[2*i0+1] * t20[2*i0];
	    t19[2*i0] = f44 - f45;
	    t19[2*i0+1] = f46 + f47;
	    }
	  /* undeftemp t20 ( 72 ) */
	  for (i0 = 0; i0 < 6; i0++) {  
	    f50 = t19[12*i0+8] - t19[12*i0+4];
	    f51 = t19[12*i0+9] - t19[12*i0+5];
	    f52 = t19[12*i0+8] + t19[12*i0+4];
	    f53 = t19[12*i0+9] + t19[12*i0+5];
	    f54 = t19[12*i0] + f52;
	    f55 = t19[12*i0+1] + f53;
	    f56 = 5.0000000000000000e-01 * f52;
	    f57 = 5.0000000000000000e-01 * f53;
	    f58 = t19[12*i0] - f56;
	    f59 = t19[12*i0+1] - f57;
	    f60 = 8.6602540378443860e-01 * f51;
	    f61 = 8.6602540378443860e-01 * f50;
	    f62 = f58 + f60;
	    f63 = f59 - f61;
	    f64 = f58 - f60;
	    f65 = f59 + f61;
	    f66 = t19[12*i0+2] - t19[12*i0+10];
	    f67 = t19[12*i0+3] - t19[12*i0+11];
	    f68 = t19[12*i0+2] + t19[12*i0+10];
	    f69 = t19[12*i0+3] + t19[12*i0+11];
	    f70 = t19[12*i0+6] + f68;
	    f71 = t19[12*i0+7] + f69;
	    f72 = 5.0000000000000000e-01 * f68;
	    f73 = 5.0000000000000000e-01 * f69;
	    f74 = t19[12*i0+6] - f72;
	    f75 = t19[12*i0+7] - f73;
	    f76 = 8.6602540378443860e-01 * f67;
	    f77 = 8.6602540378443860e-01 * f66;
	    f78 = f74 + f76;
	    f79 = f75 - f77;
	    f80 = f74 - f76;
	    f81 = f75 + f77;
	    t18[12*i0+6] = f54 - f70;
	    t18[12*i0+7] = f55 - f71;
	    t18[12*i0] = f54 + f70;
	    t18[12*i0+1] = f55 + f71;
	    t18[12*i0+10] = f64 - f80;
	    t18[12*i0+11] = f65 - f81;
	    t18[12*i0+4] = f64 + f80;
	    t18[12*i0+5] = f65 + f81;
	    t18[12*i0+2] = f62 - f78;
	    t18[12*i0+3] = f63 - f79;
	    t18[12*i0+8] = f62 + f78;
	    t18[12*i0+9] = f63 + f79;
	    }
	  /* undeftemp t19 ( 72 ) */
	  y[0] = t18[0];
	  y[1] = t18[1];
	  y[2] = t18[12];
	  y[3] = t18[13];
	  y[4] = t18[24];
	  y[5] = t18[25];
	  y[6] = t18[36];
	  y[7] = t18[37];
	  y[8] = t18[48];
	  y[9] = t18[49];
	  y[10] = t18[60];
	  y[11] = t18[61];
	  y[12] = t18[2];
	  y[13] = t18[3];
	  y[14] = t18[14];
	  y[15] = t18[15];
	  y[16] = t18[26];
	  y[17] = t18[27];
	  y[18] = t18[38];
	  y[19] = t18[39];
	  y[20] = t18[50];
	  y[21] = t18[51];
	  y[22] = t18[62];
	  y[23] = t18[63];
	  y[24] = t18[4];
	  y[25] = t18[5];
	  y[26] = t18[16];
	  y[27] = t18[17];
	  y[28] = t18[28];
	  y[29] = t18[29];
	  y[30] = t18[40];
	  y[31] = t18[41];
	  y[32] = t18[52];
	  y[33] = t18[53];
	  y[34] = t18[64];
	  y[35] = t18[65];
	  y[36] = t18[6];
	  y[37] = t18[7];
	  y[38] = t18[18];
	  y[39] = t18[19];
	  y[40] = t18[30];
	  y[41] = t18[31];
	  y[42] = t18[42];
	  y[43] = t18[43];
	  y[44] = t18[54];
	  y[45] = t18[55];
	  y[46] = t18[66];
	  y[47] = t18[67];
	  y[48] = t18[8];
	  y[49] = t18[9];
	  y[50] = t18[20];
	  y[51] = t18[21];
	  y[52] = t18[32];
	  y[53] = t18[33];
	  y[54] = t18[44];
	  y[55] = t18[45];
	  y[56] = t18[56];
	  y[57] = t18[57];
	  y[58] = t18[68];
	  y[59] = t18[69];
	  y[60] = t18[10];
	  y[61] = t18[11];
	  y[62] = t18[22];
	  y[63] = t18[23];
	  y[64] = t18[34];
	  y[65] = t18[35];
	  y[66] = t18[46];
	  y[67] = t18[47];
	  y[68] = t18[58];
	  y[69] = t18[59];
	  y[70] = t18[70];
	  y[71] = t18[71];
	  /* undeftemp t18 ( 72 ) */

	  /* undecl double t20[72]; */
	  /* undecl double t19[72]; */
	  /* undecl double t18[72]; */

	}
#include <math.h>
#ifndef NO_GLOBAL
	double T_36_6 [72];
#endif

	void init_FFT_M2X_36( void )
	{
	int i;
	int j;
	  extern double T_36_6 [72];
	  for (i=0; i<=5; i++) {
	    for (j=0; j<=5; j++) {
	      T_36_6[12*i+2*j] = (cos(6.2831853071795862e+00*i*j/36));
	      T_36_6[12*i+2*j+1] = (sin(6.2831853071795862e+00*i*j/36));
	    }
	  }

	}

