/*
! +-----------------------------------------------+
! |        Generated by SPL Compiler 3.30         |
! +-----------------------------------------------+
! Command-line options: -l -B 32 -C -xprecision=double -xposw -xsubname=FFT_X2L_8 
! 
*/
/*
! The SPL Program: (compose (permutation (1 8 7 6 5 4 3 2))(compose (direct_sum (..)(..))(compose (..)(..))))
! node size: 8 X 8
*/


	void FFT_X2L_8(double *y, double *x) {
	double f0;
	double f1;
	double f2;
	double f3;
	double f4;
	double f5;
	double f6;
	double f7;
	double f8;
	double f9;
	double f10;
	double f11;
	double f12;
	double f13;
	double f14;
	double f15;
	double f16;
	double f17;
	double f18;
	double f19;
	double f20;
	double f21;
	double f22;
	double f23;
	double f24;
	double f25;
	double f30;
	double f31;
	double f32;
	double f33;
	double f34;
	double f35;
	double f36;
	double f37;
	double f38;
	double f39;
	double f40;
	double f41;
	double f42;
	double f43;

	  f0 = x[2] - x[14];
	  f1 = x[3] - x[15];
	  f2 = x[2] + x[14];
	  f3 = x[3] + x[15];
	  f4 = x[4] - x[12];
	  f5 = x[5] - x[13];
	  f6 = x[4] + x[12];
	  f7 = x[5] + x[13];
	  f8 = x[6] - x[10];
	  f9 = x[7] - x[11];
	  f10 = x[6] + x[10];
	  f11 = x[7] + x[11];
	  f12 = x[0] - x[8];
	  f13 = x[1] - x[9];
	  f14 = x[0] + x[8];
	  f15 = x[1] + x[9];
	  f16 = f14 - f6;
	  f17 = f15 - f7;
	  f18 = f14 + f6;
	  f19 = f15 + f7;
	  f20 = f2 - f10;
	  f21 = f3 - f11;
	  f22 = f2 + f10;
	  f23 = f3 + f11;
	  f24 = 7.0710678118654757e-01 * f20;
	  f25 = 7.0710678118654757e-01 * f21;
	  y[8] = f18 - f22;
	  y[9] = f19 - f23;
	  y[0] = f18 + f22;
	  y[1] = f19 + f23;
	  f30 = f12 - f24;
	  f31 = f13 - f25;
	  f32 = f12 + f24;
	  f33 = f13 + f25;
	  f34 = f0 - f8;
	  f35 = f1 - f9;
	  f36 = f0 + f8;
	  f37 = f1 + f9;
	  f38 = 7.0710678118654757e-01 * f36;
	  f39 = 7.0710678118654757e-01 * f37;
	  f40 = f38 - f4;
	  f41 = f39 - f5;
	  f42 = f38 + f4;
	  f43 = f39 + f5;
	  y[2] = f32 + f43;
	  y[3] = f33 - f42;
	  y[14] = f32 - f43;
	  y[15] = f33 + f42;
	  y[4] = f16 + f35;
	  y[5] = f17 - f34;
	  y[12] = f16 - f35;
	  y[13] = f17 + f34;
	  y[6] = f30 + f41;
	  y[7] = f31 - f40;
	  y[10] = f30 - f41;
	  y[11] = f31 + f40;


	}
	void init_FFT_X2L_8( void )
	{
	}

