	
/* This file is automatically generated by gen_gen_neighbor_list2.py */
/* DO NOT EDIT! */

#include "_fmmv.h"
#include <string.h> /* memset */

#if (FMM_DIM==2)

enum {
	N2_m1_m1, 	N2_m1_0, 	N2_m1_1, 	N2_0_m1,
	N2_0_1, 	N2_1_m1, 	N2_1_0, 	N2_1_1,
	N2_m2_m2, 	N2_m2_m1, 	N2_m2_0, 	N2_m2_1,
	N2_m2_2, 	N2_m1_m2, 	N2_m1_2, 	N2_0_m2,
	N2_0_2, 	N2_1_m2, 	N2_1_2, 	N2_2_m2,
	N2_2_m1, 	N2_2_0, 	N2_2_1, 	N2_2_2,
};

void gen_neighbor2_list(Box *box, Box **list)
{
	Box *parent = box->parent;
	Box *nb;

	memcpy(list, box->neighbor, 8*sizeof(Box*));
	memset(list+8, 0, 16*sizeof(Box*));

	if (box->whichChild==SW) {
		nb = parent->neighbor[SW_];
		if (nb) {
			list[N2_m2_m2] = nb->child[SW];
			list[N2_m2_m1] = nb->child[NW];
			list[N2_m1_m2] = nb->child[SE];
		}
		nb = parent->neighbor[MW_];
		if (nb) {
			list[N2_m2_0] = nb->child[SW];
			list[N2_m2_1] = nb->child[NW];
		}
		nb = parent->neighbor[NW_];
		if (nb) {
			list[N2_m2_2] = nb->child[SW];
			list[N2_m1_2] = nb->child[SE];
		}
		nb = parent->neighbor[SM_];
		if (nb) {
			list[N2_0_m2] = nb->child[SW];
			list[N2_1_m2] = nb->child[SE];
		}
		nb = parent->neighbor[NM_];
		if (nb) {
			list[N2_0_2] = nb->child[SW];
			list[N2_1_2] = nb->child[SE];
		}
		nb = parent->neighbor[SE_];
		if (nb) {
			list[N2_2_m2] = nb->child[SW];
			list[N2_2_m1] = nb->child[NW];
		}
		nb = parent->neighbor[ME_];
		if (nb) {
			list[N2_2_0] = nb->child[SW];
			list[N2_2_1] = nb->child[NW];
		}
		nb = parent->neighbor[NE_];
		if (nb) {
			list[N2_2_2] = nb->child[SW];
		}
	}  /* 16 */
	if (box->whichChild==NW) {
		nb = parent->neighbor[SW_];
		if (nb) {
			list[N2_m2_m2] = nb->child[NW];
			list[N2_m1_m2] = nb->child[NE];
		}
		nb = parent->neighbor[MW_];
		if (nb) {
			list[N2_m2_m1] = nb->child[SW];
			list[N2_m2_0] = nb->child[NW];
		}
		nb = parent->neighbor[NW_];
		if (nb) {
			list[N2_m2_1] = nb->child[SW];
			list[N2_m2_2] = nb->child[NW];
			list[N2_m1_2] = nb->child[NE];
		}
		nb = parent->neighbor[SM_];
		if (nb) {
			list[N2_0_m2] = nb->child[NW];
			list[N2_1_m2] = nb->child[NE];
		}
		nb = parent->neighbor[NM_];
		if (nb) {
			list[N2_0_2] = nb->child[NW];
			list[N2_1_2] = nb->child[NE];
		}
		nb = parent->neighbor[SE_];
		if (nb) {
			list[N2_2_m2] = nb->child[NW];
		}
		nb = parent->neighbor[ME_];
		if (nb) {
			list[N2_2_m1] = nb->child[SW];
			list[N2_2_0] = nb->child[NW];
		}
		nb = parent->neighbor[NE_];
		if (nb) {
			list[N2_2_1] = nb->child[SW];
			list[N2_2_2] = nb->child[NW];
		}
	}  /* 16 */
	if (box->whichChild==SE) {
		nb = parent->neighbor[SW_];
		if (nb) {
			list[N2_m2_m2] = nb->child[SE];
			list[N2_m2_m1] = nb->child[NE];
		}
		nb = parent->neighbor[MW_];
		if (nb) {
			list[N2_m2_0] = nb->child[SE];
			list[N2_m2_1] = nb->child[NE];
		}
		nb = parent->neighbor[NW_];
		if (nb) {
			list[N2_m2_2] = nb->child[SE];
		}
		nb = parent->neighbor[SM_];
		if (nb) {
			list[N2_m1_m2] = nb->child[SW];
			list[N2_0_m2] = nb->child[SE];
		}
		nb = parent->neighbor[NM_];
		if (nb) {
			list[N2_m1_2] = nb->child[SW];
			list[N2_0_2] = nb->child[SE];
		}
		nb = parent->neighbor[SE_];
		if (nb) {
			list[N2_1_m2] = nb->child[SW];
			list[N2_2_m2] = nb->child[SE];
			list[N2_2_m1] = nb->child[NE];
		}
		nb = parent->neighbor[ME_];
		if (nb) {
			list[N2_2_0] = nb->child[SE];
			list[N2_2_1] = nb->child[NE];
		}
		nb = parent->neighbor[NE_];
		if (nb) {
			list[N2_1_2] = nb->child[SW];
			list[N2_2_2] = nb->child[SE];
		}
	}  /* 16 */
	if (box->whichChild==NE) {
		nb = parent->neighbor[SW_];
		if (nb) {
			list[N2_m2_m2] = nb->child[NE];
		}
		nb = parent->neighbor[MW_];
		if (nb) {
			list[N2_m2_m1] = nb->child[SE];
			list[N2_m2_0] = nb->child[NE];
		}
		nb = parent->neighbor[NW_];
		if (nb) {
			list[N2_m2_1] = nb->child[SE];
			list[N2_m2_2] = nb->child[NE];
		}
		nb = parent->neighbor[SM_];
		if (nb) {
			list[N2_m1_m2] = nb->child[NW];
			list[N2_0_m2] = nb->child[NE];
		}
		nb = parent->neighbor[NM_];
		if (nb) {
			list[N2_m1_2] = nb->child[NW];
			list[N2_0_2] = nb->child[NE];
		}
		nb = parent->neighbor[SE_];
		if (nb) {
			list[N2_1_m2] = nb->child[NW];
			list[N2_2_m2] = nb->child[NE];
		}
		nb = parent->neighbor[ME_];
		if (nb) {
			list[N2_2_m1] = nb->child[SE];
			list[N2_2_0] = nb->child[NE];
		}
		nb = parent->neighbor[NE_];
		if (nb) {
			list[N2_1_2] = nb->child[NW];
			list[N2_2_1] = nb->child[SE];
			list[N2_2_2] = nb->child[NE];
		}
	}  /* 16 */
}

#elif (FMM_DIM==3)

enum {
	N2_m1_m1_m1, 	N2_m1_0_m1, 	N2_m1_1_m1, 	N2_0_m1_m1,
	N2_0_0_m1, 	N2_0_1_m1, 	N2_1_m1_m1, 	N2_1_0_m1,
	N2_1_1_m1, 	N2_m1_m1_0, 	N2_m1_0_0, 	N2_m1_1_0,
	N2_0_m1_0, 	N2_0_1_0, 	N2_1_m1_0, 	N2_1_0_0,
	N2_1_1_0, 	N2_m1_m1_1, 	N2_m1_0_1, 	N2_m1_1_1,
	N2_0_m1_1, 	N2_0_0_1, 	N2_0_1_1, 	N2_1_m1_1,
	N2_1_0_1, 	N2_1_1_1, 	N2_m2_m2_m2, 	N2_m2_m2_m1,
	N2_m2_m2_0, 	N2_m2_m2_1, 	N2_m2_m2_2, 	N2_m2_m1_m2,
	N2_m2_m1_m1, 	N2_m2_m1_0, 	N2_m2_m1_1, 	N2_m2_m1_2,
	N2_m2_0_m2, 	N2_m2_0_m1, 	N2_m2_0_0, 	N2_m2_0_1,
	N2_m2_0_2, 	N2_m2_1_m2, 	N2_m2_1_m1, 	N2_m2_1_0,
	N2_m2_1_1, 	N2_m2_1_2, 	N2_m2_2_m2, 	N2_m2_2_m1,
	N2_m2_2_0, 	N2_m2_2_1, 	N2_m2_2_2, 	N2_m1_m2_m2,
	N2_m1_m2_m1, 	N2_m1_m2_0, 	N2_m1_m2_1, 	N2_m1_m2_2,
	N2_m1_m1_m2, 	N2_m1_m1_2, 	N2_m1_0_m2, 	N2_m1_0_2,
	N2_m1_1_m2, 	N2_m1_1_2, 	N2_m1_2_m2, 	N2_m1_2_m1,
	N2_m1_2_0, 	N2_m1_2_1, 	N2_m1_2_2, 	N2_0_m2_m2,
	N2_0_m2_m1, 	N2_0_m2_0, 	N2_0_m2_1, 	N2_0_m2_2,
	N2_0_m1_m2, 	N2_0_m1_2, 	N2_0_0_m2, 	N2_0_0_2,
	N2_0_1_m2, 	N2_0_1_2, 	N2_0_2_m2, 	N2_0_2_m1,
	N2_0_2_0, 	N2_0_2_1, 	N2_0_2_2, 	N2_1_m2_m2,
	N2_1_m2_m1, 	N2_1_m2_0, 	N2_1_m2_1, 	N2_1_m2_2,
	N2_1_m1_m2, 	N2_1_m1_2, 	N2_1_0_m2, 	N2_1_0_2,
	N2_1_1_m2, 	N2_1_1_2, 	N2_1_2_m2, 	N2_1_2_m1,
	N2_1_2_0, 	N2_1_2_1, 	N2_1_2_2, 	N2_2_m2_m2,
	N2_2_m2_m1, 	N2_2_m2_0, 	N2_2_m2_1, 	N2_2_m2_2,
	N2_2_m1_m2, 	N2_2_m1_m1, 	N2_2_m1_0, 	N2_2_m1_1,
	N2_2_m1_2, 	N2_2_0_m2, 	N2_2_0_m1, 	N2_2_0_0,
	N2_2_0_1, 	N2_2_0_2, 	N2_2_1_m2, 	N2_2_1_m1,
	N2_2_1_0, 	N2_2_1_1, 	N2_2_1_2, 	N2_2_2_m2,
	N2_2_2_m1, 	N2_2_2_0, 	N2_2_2_1, 	N2_2_2_2,
};

void gen_neighbor2_list(Box *box, Box **list)
{
	Box *parent = box->parent;
	Box *nb;

	memcpy(list, box->neighbor, 26*sizeof(Box*));
	memset(list+26, 0, 98*sizeof(Box*));

	if (box->whichChild==SWD) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[SWD];
			list[N2_m2_m1_m2] = nb->child[NWD];
			list[N2_m1_m2_m2] = nb->child[SED];
			list[N2_m1_m1_m2] = nb->child[NED];
			list[N2_m2_m2_m1] = nb->child[SWU];
			list[N2_m2_m1_m1] = nb->child[NWU];
			list[N2_m1_m2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_0_m2] = nb->child[SWD];
			list[N2_m2_1_m2] = nb->child[NWD];
			list[N2_m1_0_m2] = nb->child[SED];
			list[N2_m1_1_m2] = nb->child[NED];
			list[N2_m2_0_m1] = nb->child[SWU];
			list[N2_m2_1_m1] = nb->child[NWU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_2_m2] = nb->child[SWD];
			list[N2_m1_2_m2] = nb->child[SED];
			list[N2_m2_2_m1] = nb->child[SWU];
			list[N2_m1_2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_0_m2_m2] = nb->child[SWD];
			list[N2_0_m1_m2] = nb->child[NWD];
			list[N2_1_m2_m2] = nb->child[SED];
			list[N2_1_m1_m2] = nb->child[NED];
			list[N2_0_m2_m1] = nb->child[SWU];
			list[N2_1_m2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_0_0_m2] = nb->child[SWD];
			list[N2_0_1_m2] = nb->child[NWD];
			list[N2_1_0_m2] = nb->child[SED];
			list[N2_1_1_m2] = nb->child[NED];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_0_2_m2] = nb->child[SWD];
			list[N2_1_2_m2] = nb->child[SED];
			list[N2_0_2_m1] = nb->child[SWU];
			list[N2_1_2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_2_m2_m2] = nb->child[SWD];
			list[N2_2_m1_m2] = nb->child[NWD];
			list[N2_2_m2_m1] = nb->child[SWU];
			list[N2_2_m1_m1] = nb->child[NWU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_2_0_m2] = nb->child[SWD];
			list[N2_2_1_m2] = nb->child[NWD];
			list[N2_2_0_m1] = nb->child[SWU];
			list[N2_2_1_m1] = nb->child[NWU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_2_2_m2] = nb->child[SWD];
			list[N2_2_2_m1] = nb->child[SWU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_0] = nb->child[SWD];
			list[N2_m2_m1_0] = nb->child[NWD];
			list[N2_m1_m2_0] = nb->child[SED];
			list[N2_m2_m2_1] = nb->child[SWU];
			list[N2_m2_m1_1] = nb->child[NWU];
			list[N2_m1_m2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_0_0] = nb->child[SWD];
			list[N2_m2_1_0] = nb->child[NWD];
			list[N2_m2_0_1] = nb->child[SWU];
			list[N2_m2_1_1] = nb->child[NWU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_2_0] = nb->child[SWD];
			list[N2_m1_2_0] = nb->child[SED];
			list[N2_m2_2_1] = nb->child[SWU];
			list[N2_m1_2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_0_m2_0] = nb->child[SWD];
			list[N2_1_m2_0] = nb->child[SED];
			list[N2_0_m2_1] = nb->child[SWU];
			list[N2_1_m2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_0_2_0] = nb->child[SWD];
			list[N2_1_2_0] = nb->child[SED];
			list[N2_0_2_1] = nb->child[SWU];
			list[N2_1_2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_2_m2_0] = nb->child[SWD];
			list[N2_2_m1_0] = nb->child[NWD];
			list[N2_2_m2_1] = nb->child[SWU];
			list[N2_2_m1_1] = nb->child[NWU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_0_0] = nb->child[SWD];
			list[N2_2_1_0] = nb->child[NWD];
			list[N2_2_0_1] = nb->child[SWU];
			list[N2_2_1_1] = nb->child[NWU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_2_2_0] = nb->child[SWD];
			list[N2_2_2_1] = nb->child[SWU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_2] = nb->child[SWD];
			list[N2_m2_m1_2] = nb->child[NWD];
			list[N2_m1_m2_2] = nb->child[SED];
			list[N2_m1_m1_2] = nb->child[NED];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_0_2] = nb->child[SWD];
			list[N2_m2_1_2] = nb->child[NWD];
			list[N2_m1_0_2] = nb->child[SED];
			list[N2_m1_1_2] = nb->child[NED];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_2_2] = nb->child[SWD];
			list[N2_m1_2_2] = nb->child[SED];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_0_m2_2] = nb->child[SWD];
			list[N2_0_m1_2] = nb->child[NWD];
			list[N2_1_m2_2] = nb->child[SED];
			list[N2_1_m1_2] = nb->child[NED];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_0_0_2] = nb->child[SWD];
			list[N2_0_1_2] = nb->child[NWD];
			list[N2_1_0_2] = nb->child[SED];
			list[N2_1_1_2] = nb->child[NED];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_0_2_2] = nb->child[SWD];
			list[N2_1_2_2] = nb->child[SED];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_2_m2_2] = nb->child[SWD];
			list[N2_2_m1_2] = nb->child[NWD];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_2_0_2] = nb->child[SWD];
			list[N2_2_1_2] = nb->child[NWD];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_2_2_2] = nb->child[SWD];
		}
	}  /* 98 */
	if (box->whichChild==NWD) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[NWD];
			list[N2_m1_m2_m2] = nb->child[NED];
			list[N2_m2_m2_m1] = nb->child[NWU];
			list[N2_m1_m2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_m1_m2] = nb->child[SWD];
			list[N2_m2_0_m2] = nb->child[NWD];
			list[N2_m1_m1_m2] = nb->child[SED];
			list[N2_m1_0_m2] = nb->child[NED];
			list[N2_m2_m1_m1] = nb->child[SWU];
			list[N2_m2_0_m1] = nb->child[NWU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_1_m2] = nb->child[SWD];
			list[N2_m2_2_m2] = nb->child[NWD];
			list[N2_m1_1_m2] = nb->child[SED];
			list[N2_m1_2_m2] = nb->child[NED];
			list[N2_m2_1_m1] = nb->child[SWU];
			list[N2_m2_2_m1] = nb->child[NWU];
			list[N2_m1_2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_0_m2_m2] = nb->child[NWD];
			list[N2_1_m2_m2] = nb->child[NED];
			list[N2_0_m2_m1] = nb->child[NWU];
			list[N2_1_m2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_0_m1_m2] = nb->child[SWD];
			list[N2_0_0_m2] = nb->child[NWD];
			list[N2_1_m1_m2] = nb->child[SED];
			list[N2_1_0_m2] = nb->child[NED];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_0_1_m2] = nb->child[SWD];
			list[N2_0_2_m2] = nb->child[NWD];
			list[N2_1_1_m2] = nb->child[SED];
			list[N2_1_2_m2] = nb->child[NED];
			list[N2_0_2_m1] = nb->child[NWU];
			list[N2_1_2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_2_m2_m2] = nb->child[NWD];
			list[N2_2_m2_m1] = nb->child[NWU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_2_m1_m2] = nb->child[SWD];
			list[N2_2_0_m2] = nb->child[NWD];
			list[N2_2_m1_m1] = nb->child[SWU];
			list[N2_2_0_m1] = nb->child[NWU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_2_1_m2] = nb->child[SWD];
			list[N2_2_2_m2] = nb->child[NWD];
			list[N2_2_1_m1] = nb->child[SWU];
			list[N2_2_2_m1] = nb->child[NWU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_0] = nb->child[NWD];
			list[N2_m1_m2_0] = nb->child[NED];
			list[N2_m2_m2_1] = nb->child[NWU];
			list[N2_m1_m2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_m1_0] = nb->child[SWD];
			list[N2_m2_0_0] = nb->child[NWD];
			list[N2_m2_m1_1] = nb->child[SWU];
			list[N2_m2_0_1] = nb->child[NWU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_1_0] = nb->child[SWD];
			list[N2_m2_2_0] = nb->child[NWD];
			list[N2_m1_2_0] = nb->child[NED];
			list[N2_m2_1_1] = nb->child[SWU];
			list[N2_m2_2_1] = nb->child[NWU];
			list[N2_m1_2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_0_m2_0] = nb->child[NWD];
			list[N2_1_m2_0] = nb->child[NED];
			list[N2_0_m2_1] = nb->child[NWU];
			list[N2_1_m2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_0_2_0] = nb->child[NWD];
			list[N2_1_2_0] = nb->child[NED];
			list[N2_0_2_1] = nb->child[NWU];
			list[N2_1_2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_2_m2_0] = nb->child[NWD];
			list[N2_2_m2_1] = nb->child[NWU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_m1_0] = nb->child[SWD];
			list[N2_2_0_0] = nb->child[NWD];
			list[N2_2_m1_1] = nb->child[SWU];
			list[N2_2_0_1] = nb->child[NWU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_2_1_0] = nb->child[SWD];
			list[N2_2_2_0] = nb->child[NWD];
			list[N2_2_1_1] = nb->child[SWU];
			list[N2_2_2_1] = nb->child[NWU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_2] = nb->child[NWD];
			list[N2_m1_m2_2] = nb->child[NED];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_m1_2] = nb->child[SWD];
			list[N2_m2_0_2] = nb->child[NWD];
			list[N2_m1_m1_2] = nb->child[SED];
			list[N2_m1_0_2] = nb->child[NED];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_1_2] = nb->child[SWD];
			list[N2_m2_2_2] = nb->child[NWD];
			list[N2_m1_1_2] = nb->child[SED];
			list[N2_m1_2_2] = nb->child[NED];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_0_m2_2] = nb->child[NWD];
			list[N2_1_m2_2] = nb->child[NED];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_0_m1_2] = nb->child[SWD];
			list[N2_0_0_2] = nb->child[NWD];
			list[N2_1_m1_2] = nb->child[SED];
			list[N2_1_0_2] = nb->child[NED];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_0_1_2] = nb->child[SWD];
			list[N2_0_2_2] = nb->child[NWD];
			list[N2_1_1_2] = nb->child[SED];
			list[N2_1_2_2] = nb->child[NED];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_2_m2_2] = nb->child[NWD];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_2_m1_2] = nb->child[SWD];
			list[N2_2_0_2] = nb->child[NWD];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_2_1_2] = nb->child[SWD];
			list[N2_2_2_2] = nb->child[NWD];
		}
	}  /* 98 */
	if (box->whichChild==SED) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[SED];
			list[N2_m2_m1_m2] = nb->child[NED];
			list[N2_m2_m2_m1] = nb->child[SEU];
			list[N2_m2_m1_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_0_m2] = nb->child[SED];
			list[N2_m2_1_m2] = nb->child[NED];
			list[N2_m2_0_m1] = nb->child[SEU];
			list[N2_m2_1_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_2_m2] = nb->child[SED];
			list[N2_m2_2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_m1_m2_m2] = nb->child[SWD];
			list[N2_m1_m1_m2] = nb->child[NWD];
			list[N2_0_m2_m2] = nb->child[SED];
			list[N2_0_m1_m2] = nb->child[NED];
			list[N2_m1_m2_m1] = nb->child[SWU];
			list[N2_0_m2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_m1_0_m2] = nb->child[SWD];
			list[N2_m1_1_m2] = nb->child[NWD];
			list[N2_0_0_m2] = nb->child[SED];
			list[N2_0_1_m2] = nb->child[NED];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_m1_2_m2] = nb->child[SWD];
			list[N2_0_2_m2] = nb->child[SED];
			list[N2_m1_2_m1] = nb->child[SWU];
			list[N2_0_2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_1_m2_m2] = nb->child[SWD];
			list[N2_1_m1_m2] = nb->child[NWD];
			list[N2_2_m2_m2] = nb->child[SED];
			list[N2_2_m1_m2] = nb->child[NED];
			list[N2_1_m2_m1] = nb->child[SWU];
			list[N2_2_m2_m1] = nb->child[SEU];
			list[N2_2_m1_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_1_0_m2] = nb->child[SWD];
			list[N2_1_1_m2] = nb->child[NWD];
			list[N2_2_0_m2] = nb->child[SED];
			list[N2_2_1_m2] = nb->child[NED];
			list[N2_2_0_m1] = nb->child[SEU];
			list[N2_2_1_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_1_2_m2] = nb->child[SWD];
			list[N2_2_2_m2] = nb->child[SED];
			list[N2_1_2_m1] = nb->child[SWU];
			list[N2_2_2_m1] = nb->child[SEU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_0] = nb->child[SED];
			list[N2_m2_m1_0] = nb->child[NED];
			list[N2_m2_m2_1] = nb->child[SEU];
			list[N2_m2_m1_1] = nb->child[NEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_0_0] = nb->child[SED];
			list[N2_m2_1_0] = nb->child[NED];
			list[N2_m2_0_1] = nb->child[SEU];
			list[N2_m2_1_1] = nb->child[NEU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_2_0] = nb->child[SED];
			list[N2_m2_2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_m1_m2_0] = nb->child[SWD];
			list[N2_0_m2_0] = nb->child[SED];
			list[N2_m1_m2_1] = nb->child[SWU];
			list[N2_0_m2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_m1_2_0] = nb->child[SWD];
			list[N2_0_2_0] = nb->child[SED];
			list[N2_m1_2_1] = nb->child[SWU];
			list[N2_0_2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_1_m2_0] = nb->child[SWD];
			list[N2_2_m2_0] = nb->child[SED];
			list[N2_2_m1_0] = nb->child[NED];
			list[N2_1_m2_1] = nb->child[SWU];
			list[N2_2_m2_1] = nb->child[SEU];
			list[N2_2_m1_1] = nb->child[NEU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_0_0] = nb->child[SED];
			list[N2_2_1_0] = nb->child[NED];
			list[N2_2_0_1] = nb->child[SEU];
			list[N2_2_1_1] = nb->child[NEU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_1_2_0] = nb->child[SWD];
			list[N2_2_2_0] = nb->child[SED];
			list[N2_1_2_1] = nb->child[SWU];
			list[N2_2_2_1] = nb->child[SEU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_2] = nb->child[SED];
			list[N2_m2_m1_2] = nb->child[NED];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_0_2] = nb->child[SED];
			list[N2_m2_1_2] = nb->child[NED];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_2_2] = nb->child[SED];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_m1_m2_2] = nb->child[SWD];
			list[N2_m1_m1_2] = nb->child[NWD];
			list[N2_0_m2_2] = nb->child[SED];
			list[N2_0_m1_2] = nb->child[NED];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_m1_0_2] = nb->child[SWD];
			list[N2_m1_1_2] = nb->child[NWD];
			list[N2_0_0_2] = nb->child[SED];
			list[N2_0_1_2] = nb->child[NED];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_m1_2_2] = nb->child[SWD];
			list[N2_0_2_2] = nb->child[SED];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_1_m2_2] = nb->child[SWD];
			list[N2_1_m1_2] = nb->child[NWD];
			list[N2_2_m2_2] = nb->child[SED];
			list[N2_2_m1_2] = nb->child[NED];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_1_0_2] = nb->child[SWD];
			list[N2_1_1_2] = nb->child[NWD];
			list[N2_2_0_2] = nb->child[SED];
			list[N2_2_1_2] = nb->child[NED];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_1_2_2] = nb->child[SWD];
			list[N2_2_2_2] = nb->child[SED];
		}
	}  /* 98 */
	if (box->whichChild==NED) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[NED];
			list[N2_m2_m2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_m1_m2] = nb->child[SED];
			list[N2_m2_0_m2] = nb->child[NED];
			list[N2_m2_m1_m1] = nb->child[SEU];
			list[N2_m2_0_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_1_m2] = nb->child[SED];
			list[N2_m2_2_m2] = nb->child[NED];
			list[N2_m2_1_m1] = nb->child[SEU];
			list[N2_m2_2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_m1_m2_m2] = nb->child[NWD];
			list[N2_0_m2_m2] = nb->child[NED];
			list[N2_m1_m2_m1] = nb->child[NWU];
			list[N2_0_m2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_m1_m1_m2] = nb->child[SWD];
			list[N2_m1_0_m2] = nb->child[NWD];
			list[N2_0_m1_m2] = nb->child[SED];
			list[N2_0_0_m2] = nb->child[NED];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_m1_1_m2] = nb->child[SWD];
			list[N2_m1_2_m2] = nb->child[NWD];
			list[N2_0_1_m2] = nb->child[SED];
			list[N2_0_2_m2] = nb->child[NED];
			list[N2_m1_2_m1] = nb->child[NWU];
			list[N2_0_2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_1_m2_m2] = nb->child[NWD];
			list[N2_2_m2_m2] = nb->child[NED];
			list[N2_1_m2_m1] = nb->child[NWU];
			list[N2_2_m2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_1_m1_m2] = nb->child[SWD];
			list[N2_1_0_m2] = nb->child[NWD];
			list[N2_2_m1_m2] = nb->child[SED];
			list[N2_2_0_m2] = nb->child[NED];
			list[N2_2_m1_m1] = nb->child[SEU];
			list[N2_2_0_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_1_1_m2] = nb->child[SWD];
			list[N2_1_2_m2] = nb->child[NWD];
			list[N2_2_1_m2] = nb->child[SED];
			list[N2_2_2_m2] = nb->child[NED];
			list[N2_1_2_m1] = nb->child[NWU];
			list[N2_2_1_m1] = nb->child[SEU];
			list[N2_2_2_m1] = nb->child[NEU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_0] = nb->child[NED];
			list[N2_m2_m2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_m1_0] = nb->child[SED];
			list[N2_m2_0_0] = nb->child[NED];
			list[N2_m2_m1_1] = nb->child[SEU];
			list[N2_m2_0_1] = nb->child[NEU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_1_0] = nb->child[SED];
			list[N2_m2_2_0] = nb->child[NED];
			list[N2_m2_1_1] = nb->child[SEU];
			list[N2_m2_2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_m1_m2_0] = nb->child[NWD];
			list[N2_0_m2_0] = nb->child[NED];
			list[N2_m1_m2_1] = nb->child[NWU];
			list[N2_0_m2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_m1_2_0] = nb->child[NWD];
			list[N2_0_2_0] = nb->child[NED];
			list[N2_m1_2_1] = nb->child[NWU];
			list[N2_0_2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_1_m2_0] = nb->child[NWD];
			list[N2_2_m2_0] = nb->child[NED];
			list[N2_1_m2_1] = nb->child[NWU];
			list[N2_2_m2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_m1_0] = nb->child[SED];
			list[N2_2_0_0] = nb->child[NED];
			list[N2_2_m1_1] = nb->child[SEU];
			list[N2_2_0_1] = nb->child[NEU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_1_2_0] = nb->child[NWD];
			list[N2_2_1_0] = nb->child[SED];
			list[N2_2_2_0] = nb->child[NED];
			list[N2_1_2_1] = nb->child[NWU];
			list[N2_2_1_1] = nb->child[SEU];
			list[N2_2_2_1] = nb->child[NEU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_2] = nb->child[NED];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_m1_2] = nb->child[SED];
			list[N2_m2_0_2] = nb->child[NED];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_1_2] = nb->child[SED];
			list[N2_m2_2_2] = nb->child[NED];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_m1_m2_2] = nb->child[NWD];
			list[N2_0_m2_2] = nb->child[NED];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_m1_m1_2] = nb->child[SWD];
			list[N2_m1_0_2] = nb->child[NWD];
			list[N2_0_m1_2] = nb->child[SED];
			list[N2_0_0_2] = nb->child[NED];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_m1_1_2] = nb->child[SWD];
			list[N2_m1_2_2] = nb->child[NWD];
			list[N2_0_1_2] = nb->child[SED];
			list[N2_0_2_2] = nb->child[NED];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_1_m2_2] = nb->child[NWD];
			list[N2_2_m2_2] = nb->child[NED];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_1_m1_2] = nb->child[SWD];
			list[N2_1_0_2] = nb->child[NWD];
			list[N2_2_m1_2] = nb->child[SED];
			list[N2_2_0_2] = nb->child[NED];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_1_1_2] = nb->child[SWD];
			list[N2_1_2_2] = nb->child[NWD];
			list[N2_2_1_2] = nb->child[SED];
			list[N2_2_2_2] = nb->child[NED];
		}
	}  /* 98 */
	if (box->whichChild==SWU) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[SWU];
			list[N2_m2_m1_m2] = nb->child[NWU];
			list[N2_m1_m2_m2] = nb->child[SEU];
			list[N2_m1_m1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_0_m2] = nb->child[SWU];
			list[N2_m2_1_m2] = nb->child[NWU];
			list[N2_m1_0_m2] = nb->child[SEU];
			list[N2_m1_1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_2_m2] = nb->child[SWU];
			list[N2_m1_2_m2] = nb->child[SEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_0_m2_m2] = nb->child[SWU];
			list[N2_0_m1_m2] = nb->child[NWU];
			list[N2_1_m2_m2] = nb->child[SEU];
			list[N2_1_m1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_0_0_m2] = nb->child[SWU];
			list[N2_0_1_m2] = nb->child[NWU];
			list[N2_1_0_m2] = nb->child[SEU];
			list[N2_1_1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_0_2_m2] = nb->child[SWU];
			list[N2_1_2_m2] = nb->child[SEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_2_m2_m2] = nb->child[SWU];
			list[N2_2_m1_m2] = nb->child[NWU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_2_0_m2] = nb->child[SWU];
			list[N2_2_1_m2] = nb->child[NWU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_2_2_m2] = nb->child[SWU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_m1] = nb->child[SWD];
			list[N2_m2_m1_m1] = nb->child[NWD];
			list[N2_m1_m2_m1] = nb->child[SED];
			list[N2_m2_m2_0] = nb->child[SWU];
			list[N2_m2_m1_0] = nb->child[NWU];
			list[N2_m1_m2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_0_m1] = nb->child[SWD];
			list[N2_m2_1_m1] = nb->child[NWD];
			list[N2_m2_0_0] = nb->child[SWU];
			list[N2_m2_1_0] = nb->child[NWU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_2_m1] = nb->child[SWD];
			list[N2_m1_2_m1] = nb->child[SED];
			list[N2_m2_2_0] = nb->child[SWU];
			list[N2_m1_2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_0_m2_m1] = nb->child[SWD];
			list[N2_1_m2_m1] = nb->child[SED];
			list[N2_0_m2_0] = nb->child[SWU];
			list[N2_1_m2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_0_2_m1] = nb->child[SWD];
			list[N2_1_2_m1] = nb->child[SED];
			list[N2_0_2_0] = nb->child[SWU];
			list[N2_1_2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_2_m2_m1] = nb->child[SWD];
			list[N2_2_m1_m1] = nb->child[NWD];
			list[N2_2_m2_0] = nb->child[SWU];
			list[N2_2_m1_0] = nb->child[NWU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_0_m1] = nb->child[SWD];
			list[N2_2_1_m1] = nb->child[NWD];
			list[N2_2_0_0] = nb->child[SWU];
			list[N2_2_1_0] = nb->child[NWU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_2_2_m1] = nb->child[SWD];
			list[N2_2_2_0] = nb->child[SWU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_1] = nb->child[SWD];
			list[N2_m2_m1_1] = nb->child[NWD];
			list[N2_m1_m2_1] = nb->child[SED];
			list[N2_m2_m2_2] = nb->child[SWU];
			list[N2_m2_m1_2] = nb->child[NWU];
			list[N2_m1_m2_2] = nb->child[SEU];
			list[N2_m1_m1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_0_1] = nb->child[SWD];
			list[N2_m2_1_1] = nb->child[NWD];
			list[N2_m2_0_2] = nb->child[SWU];
			list[N2_m2_1_2] = nb->child[NWU];
			list[N2_m1_0_2] = nb->child[SEU];
			list[N2_m1_1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_2_1] = nb->child[SWD];
			list[N2_m1_2_1] = nb->child[SED];
			list[N2_m2_2_2] = nb->child[SWU];
			list[N2_m1_2_2] = nb->child[SEU];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_0_m2_1] = nb->child[SWD];
			list[N2_1_m2_1] = nb->child[SED];
			list[N2_0_m2_2] = nb->child[SWU];
			list[N2_0_m1_2] = nb->child[NWU];
			list[N2_1_m2_2] = nb->child[SEU];
			list[N2_1_m1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_0_0_2] = nb->child[SWU];
			list[N2_0_1_2] = nb->child[NWU];
			list[N2_1_0_2] = nb->child[SEU];
			list[N2_1_1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_0_2_1] = nb->child[SWD];
			list[N2_1_2_1] = nb->child[SED];
			list[N2_0_2_2] = nb->child[SWU];
			list[N2_1_2_2] = nb->child[SEU];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_2_m2_1] = nb->child[SWD];
			list[N2_2_m1_1] = nb->child[NWD];
			list[N2_2_m2_2] = nb->child[SWU];
			list[N2_2_m1_2] = nb->child[NWU];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_2_0_1] = nb->child[SWD];
			list[N2_2_1_1] = nb->child[NWD];
			list[N2_2_0_2] = nb->child[SWU];
			list[N2_2_1_2] = nb->child[NWU];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_2_2_1] = nb->child[SWD];
			list[N2_2_2_2] = nb->child[SWU];
		}
	}  /* 98 */
	if (box->whichChild==NWU) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[NWU];
			list[N2_m1_m2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_m1_m2] = nb->child[SWU];
			list[N2_m2_0_m2] = nb->child[NWU];
			list[N2_m1_m1_m2] = nb->child[SEU];
			list[N2_m1_0_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_1_m2] = nb->child[SWU];
			list[N2_m2_2_m2] = nb->child[NWU];
			list[N2_m1_1_m2] = nb->child[SEU];
			list[N2_m1_2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_0_m2_m2] = nb->child[NWU];
			list[N2_1_m2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_0_m1_m2] = nb->child[SWU];
			list[N2_0_0_m2] = nb->child[NWU];
			list[N2_1_m1_m2] = nb->child[SEU];
			list[N2_1_0_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_0_1_m2] = nb->child[SWU];
			list[N2_0_2_m2] = nb->child[NWU];
			list[N2_1_1_m2] = nb->child[SEU];
			list[N2_1_2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_2_m2_m2] = nb->child[NWU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_2_m1_m2] = nb->child[SWU];
			list[N2_2_0_m2] = nb->child[NWU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_2_1_m2] = nb->child[SWU];
			list[N2_2_2_m2] = nb->child[NWU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_m1] = nb->child[NWD];
			list[N2_m1_m2_m1] = nb->child[NED];
			list[N2_m2_m2_0] = nb->child[NWU];
			list[N2_m1_m2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_m1_m1] = nb->child[SWD];
			list[N2_m2_0_m1] = nb->child[NWD];
			list[N2_m2_m1_0] = nb->child[SWU];
			list[N2_m2_0_0] = nb->child[NWU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_1_m1] = nb->child[SWD];
			list[N2_m2_2_m1] = nb->child[NWD];
			list[N2_m1_2_m1] = nb->child[NED];
			list[N2_m2_1_0] = nb->child[SWU];
			list[N2_m2_2_0] = nb->child[NWU];
			list[N2_m1_2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_0_m2_m1] = nb->child[NWD];
			list[N2_1_m2_m1] = nb->child[NED];
			list[N2_0_m2_0] = nb->child[NWU];
			list[N2_1_m2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_0_2_m1] = nb->child[NWD];
			list[N2_1_2_m1] = nb->child[NED];
			list[N2_0_2_0] = nb->child[NWU];
			list[N2_1_2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_2_m2_m1] = nb->child[NWD];
			list[N2_2_m2_0] = nb->child[NWU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_m1_m1] = nb->child[SWD];
			list[N2_2_0_m1] = nb->child[NWD];
			list[N2_2_m1_0] = nb->child[SWU];
			list[N2_2_0_0] = nb->child[NWU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_2_1_m1] = nb->child[SWD];
			list[N2_2_2_m1] = nb->child[NWD];
			list[N2_2_1_0] = nb->child[SWU];
			list[N2_2_2_0] = nb->child[NWU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_1] = nb->child[NWD];
			list[N2_m1_m2_1] = nb->child[NED];
			list[N2_m2_m2_2] = nb->child[NWU];
			list[N2_m1_m2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_m1_1] = nb->child[SWD];
			list[N2_m2_0_1] = nb->child[NWD];
			list[N2_m2_m1_2] = nb->child[SWU];
			list[N2_m2_0_2] = nb->child[NWU];
			list[N2_m1_m1_2] = nb->child[SEU];
			list[N2_m1_0_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_1_1] = nb->child[SWD];
			list[N2_m2_2_1] = nb->child[NWD];
			list[N2_m1_2_1] = nb->child[NED];
			list[N2_m2_1_2] = nb->child[SWU];
			list[N2_m2_2_2] = nb->child[NWU];
			list[N2_m1_1_2] = nb->child[SEU];
			list[N2_m1_2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_0_m2_1] = nb->child[NWD];
			list[N2_1_m2_1] = nb->child[NED];
			list[N2_0_m2_2] = nb->child[NWU];
			list[N2_1_m2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_0_m1_2] = nb->child[SWU];
			list[N2_0_0_2] = nb->child[NWU];
			list[N2_1_m1_2] = nb->child[SEU];
			list[N2_1_0_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_0_2_1] = nb->child[NWD];
			list[N2_1_2_1] = nb->child[NED];
			list[N2_0_1_2] = nb->child[SWU];
			list[N2_0_2_2] = nb->child[NWU];
			list[N2_1_1_2] = nb->child[SEU];
			list[N2_1_2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_2_m2_1] = nb->child[NWD];
			list[N2_2_m2_2] = nb->child[NWU];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_2_m1_1] = nb->child[SWD];
			list[N2_2_0_1] = nb->child[NWD];
			list[N2_2_m1_2] = nb->child[SWU];
			list[N2_2_0_2] = nb->child[NWU];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_2_1_1] = nb->child[SWD];
			list[N2_2_2_1] = nb->child[NWD];
			list[N2_2_1_2] = nb->child[SWU];
			list[N2_2_2_2] = nb->child[NWU];
		}
	}  /* 98 */
	if (box->whichChild==SEU) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[SEU];
			list[N2_m2_m1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_0_m2] = nb->child[SEU];
			list[N2_m2_1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_2_m2] = nb->child[SEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_m1_m2_m2] = nb->child[SWU];
			list[N2_m1_m1_m2] = nb->child[NWU];
			list[N2_0_m2_m2] = nb->child[SEU];
			list[N2_0_m1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_m1_0_m2] = nb->child[SWU];
			list[N2_m1_1_m2] = nb->child[NWU];
			list[N2_0_0_m2] = nb->child[SEU];
			list[N2_0_1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_m1_2_m2] = nb->child[SWU];
			list[N2_0_2_m2] = nb->child[SEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_1_m2_m2] = nb->child[SWU];
			list[N2_1_m1_m2] = nb->child[NWU];
			list[N2_2_m2_m2] = nb->child[SEU];
			list[N2_2_m1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_1_0_m2] = nb->child[SWU];
			list[N2_1_1_m2] = nb->child[NWU];
			list[N2_2_0_m2] = nb->child[SEU];
			list[N2_2_1_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_1_2_m2] = nb->child[SWU];
			list[N2_2_2_m2] = nb->child[SEU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_m1] = nb->child[SED];
			list[N2_m2_m1_m1] = nb->child[NED];
			list[N2_m2_m2_0] = nb->child[SEU];
			list[N2_m2_m1_0] = nb->child[NEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_0_m1] = nb->child[SED];
			list[N2_m2_1_m1] = nb->child[NED];
			list[N2_m2_0_0] = nb->child[SEU];
			list[N2_m2_1_0] = nb->child[NEU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_2_m1] = nb->child[SED];
			list[N2_m2_2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_m1_m2_m1] = nb->child[SWD];
			list[N2_0_m2_m1] = nb->child[SED];
			list[N2_m1_m2_0] = nb->child[SWU];
			list[N2_0_m2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_m1_2_m1] = nb->child[SWD];
			list[N2_0_2_m1] = nb->child[SED];
			list[N2_m1_2_0] = nb->child[SWU];
			list[N2_0_2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_1_m2_m1] = nb->child[SWD];
			list[N2_2_m2_m1] = nb->child[SED];
			list[N2_2_m1_m1] = nb->child[NED];
			list[N2_1_m2_0] = nb->child[SWU];
			list[N2_2_m2_0] = nb->child[SEU];
			list[N2_2_m1_0] = nb->child[NEU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_0_m1] = nb->child[SED];
			list[N2_2_1_m1] = nb->child[NED];
			list[N2_2_0_0] = nb->child[SEU];
			list[N2_2_1_0] = nb->child[NEU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_1_2_m1] = nb->child[SWD];
			list[N2_2_2_m1] = nb->child[SED];
			list[N2_1_2_0] = nb->child[SWU];
			list[N2_2_2_0] = nb->child[SEU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_1] = nb->child[SED];
			list[N2_m2_m1_1] = nb->child[NED];
			list[N2_m2_m2_2] = nb->child[SEU];
			list[N2_m2_m1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_0_1] = nb->child[SED];
			list[N2_m2_1_1] = nb->child[NED];
			list[N2_m2_0_2] = nb->child[SEU];
			list[N2_m2_1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_2_1] = nb->child[SED];
			list[N2_m2_2_2] = nb->child[SEU];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_m1_m2_1] = nb->child[SWD];
			list[N2_0_m2_1] = nb->child[SED];
			list[N2_m1_m2_2] = nb->child[SWU];
			list[N2_m1_m1_2] = nb->child[NWU];
			list[N2_0_m2_2] = nb->child[SEU];
			list[N2_0_m1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_m1_0_2] = nb->child[SWU];
			list[N2_m1_1_2] = nb->child[NWU];
			list[N2_0_0_2] = nb->child[SEU];
			list[N2_0_1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_m1_2_1] = nb->child[SWD];
			list[N2_0_2_1] = nb->child[SED];
			list[N2_m1_2_2] = nb->child[SWU];
			list[N2_0_2_2] = nb->child[SEU];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_1_m2_1] = nb->child[SWD];
			list[N2_2_m2_1] = nb->child[SED];
			list[N2_2_m1_1] = nb->child[NED];
			list[N2_1_m2_2] = nb->child[SWU];
			list[N2_1_m1_2] = nb->child[NWU];
			list[N2_2_m2_2] = nb->child[SEU];
			list[N2_2_m1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_2_0_1] = nb->child[SED];
			list[N2_2_1_1] = nb->child[NED];
			list[N2_1_0_2] = nb->child[SWU];
			list[N2_1_1_2] = nb->child[NWU];
			list[N2_2_0_2] = nb->child[SEU];
			list[N2_2_1_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_1_2_1] = nb->child[SWD];
			list[N2_2_2_1] = nb->child[SED];
			list[N2_1_2_2] = nb->child[SWU];
			list[N2_2_2_2] = nb->child[SEU];
		}
	}  /* 98 */
	if (box->whichChild==NEU) {
		nb = parent->neighbor[SWD_];
		if (nb) {
			list[N2_m2_m2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWD_];
		if (nb) {
			list[N2_m2_m1_m2] = nb->child[SEU];
			list[N2_m2_0_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWD_];
		if (nb) {
			list[N2_m2_1_m2] = nb->child[SEU];
			list[N2_m2_2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[SMD_];
		if (nb) {
			list[N2_m1_m2_m2] = nb->child[NWU];
			list[N2_0_m2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMD_];
		if (nb) {
			list[N2_m1_m1_m2] = nb->child[SWU];
			list[N2_m1_0_m2] = nb->child[NWU];
			list[N2_0_m1_m2] = nb->child[SEU];
			list[N2_0_0_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMD_];
		if (nb) {
			list[N2_m1_1_m2] = nb->child[SWU];
			list[N2_m1_2_m2] = nb->child[NWU];
			list[N2_0_1_m2] = nb->child[SEU];
			list[N2_0_2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[SED_];
		if (nb) {
			list[N2_1_m2_m2] = nb->child[NWU];
			list[N2_2_m2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[MED_];
		if (nb) {
			list[N2_1_m1_m2] = nb->child[SWU];
			list[N2_1_0_m2] = nb->child[NWU];
			list[N2_2_m1_m2] = nb->child[SEU];
			list[N2_2_0_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[NED_];
		if (nb) {
			list[N2_1_1_m2] = nb->child[SWU];
			list[N2_1_2_m2] = nb->child[NWU];
			list[N2_2_1_m2] = nb->child[SEU];
			list[N2_2_2_m2] = nb->child[NEU];
		}
		nb = parent->neighbor[SWM_];
		if (nb) {
			list[N2_m2_m2_m1] = nb->child[NED];
			list[N2_m2_m2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[MWM_];
		if (nb) {
			list[N2_m2_m1_m1] = nb->child[SED];
			list[N2_m2_0_m1] = nb->child[NED];
			list[N2_m2_m1_0] = nb->child[SEU];
			list[N2_m2_0_0] = nb->child[NEU];
		}
		nb = parent->neighbor[NWM_];
		if (nb) {
			list[N2_m2_1_m1] = nb->child[SED];
			list[N2_m2_2_m1] = nb->child[NED];
			list[N2_m2_1_0] = nb->child[SEU];
			list[N2_m2_2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[SMM_];
		if (nb) {
			list[N2_m1_m2_m1] = nb->child[NWD];
			list[N2_0_m2_m1] = nb->child[NED];
			list[N2_m1_m2_0] = nb->child[NWU];
			list[N2_0_m2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[NMM_];
		if (nb) {
			list[N2_m1_2_m1] = nb->child[NWD];
			list[N2_0_2_m1] = nb->child[NED];
			list[N2_m1_2_0] = nb->child[NWU];
			list[N2_0_2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[SEM_];
		if (nb) {
			list[N2_1_m2_m1] = nb->child[NWD];
			list[N2_2_m2_m1] = nb->child[NED];
			list[N2_1_m2_0] = nb->child[NWU];
			list[N2_2_m2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[MEM_];
		if (nb) {
			list[N2_2_m1_m1] = nb->child[SED];
			list[N2_2_0_m1] = nb->child[NED];
			list[N2_2_m1_0] = nb->child[SEU];
			list[N2_2_0_0] = nb->child[NEU];
		}
		nb = parent->neighbor[NEM_];
		if (nb) {
			list[N2_1_2_m1] = nb->child[NWD];
			list[N2_2_1_m1] = nb->child[SED];
			list[N2_2_2_m1] = nb->child[NED];
			list[N2_1_2_0] = nb->child[NWU];
			list[N2_2_1_0] = nb->child[SEU];
			list[N2_2_2_0] = nb->child[NEU];
		}
		nb = parent->neighbor[SWU_];
		if (nb) {
			list[N2_m2_m2_1] = nb->child[NED];
			list[N2_m2_m2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MWU_];
		if (nb) {
			list[N2_m2_m1_1] = nb->child[SED];
			list[N2_m2_0_1] = nb->child[NED];
			list[N2_m2_m1_2] = nb->child[SEU];
			list[N2_m2_0_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NWU_];
		if (nb) {
			list[N2_m2_1_1] = nb->child[SED];
			list[N2_m2_2_1] = nb->child[NED];
			list[N2_m2_1_2] = nb->child[SEU];
			list[N2_m2_2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[SMU_];
		if (nb) {
			list[N2_m1_m2_1] = nb->child[NWD];
			list[N2_0_m2_1] = nb->child[NED];
			list[N2_m1_m2_2] = nb->child[NWU];
			list[N2_0_m2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MMU_];
		if (nb) {
			list[N2_m1_m1_2] = nb->child[SWU];
			list[N2_m1_0_2] = nb->child[NWU];
			list[N2_0_m1_2] = nb->child[SEU];
			list[N2_0_0_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NMU_];
		if (nb) {
			list[N2_m1_2_1] = nb->child[NWD];
			list[N2_0_2_1] = nb->child[NED];
			list[N2_m1_1_2] = nb->child[SWU];
			list[N2_m1_2_2] = nb->child[NWU];
			list[N2_0_1_2] = nb->child[SEU];
			list[N2_0_2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[SEU_];
		if (nb) {
			list[N2_1_m2_1] = nb->child[NWD];
			list[N2_2_m2_1] = nb->child[NED];
			list[N2_1_m2_2] = nb->child[NWU];
			list[N2_2_m2_2] = nb->child[NEU];
		}
		nb = parent->neighbor[MEU_];
		if (nb) {
			list[N2_2_m1_1] = nb->child[SED];
			list[N2_2_0_1] = nb->child[NED];
			list[N2_1_m1_2] = nb->child[SWU];
			list[N2_1_0_2] = nb->child[NWU];
			list[N2_2_m1_2] = nb->child[SEU];
			list[N2_2_0_2] = nb->child[NEU];
		}
		nb = parent->neighbor[NEU_];
		if (nb) {
			list[N2_1_2_1] = nb->child[NWD];
			list[N2_2_1_1] = nb->child[SED];
			list[N2_2_2_1] = nb->child[NED];
			list[N2_1_1_2] = nb->child[SWU];
			list[N2_1_2_2] = nb->child[NWU];
			list[N2_2_1_2] = nb->child[SEU];
			list[N2_2_2_2] = nb->child[NEU];
		}
	}  /* 98 */
}

#endif /* FMM_DIM==3 */
