/* This file is automatically generated by gen_ida.py */
/* DO NOT EDIT! */

#undef USE_LOCAL_ALIASES
#include"_fmmv.h"

#if (FMM_PRECISION==0)
static int ida_allocate_standard(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_standard_t));
	if (!FMMV->DATA) goto _err;
	((DATA_standard_t*)FMMV->DATA)->_0 = (_DATA_standard_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_standard_V0_t)); 
	if (!((DATA_standard_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_standard(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_standard_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_standard_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_standard_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_standard(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_standard_t));
	if (!FMMV->DATA) goto _err;
	((DATA_standard_t*)FMMV->DATA)->_0 = (_DATA_standard_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_standard_V0_t)); 
	if (!((DATA_standard_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_standard(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_standard_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_standard_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_standard_t));
}


#endif /* FMM_PRECISION */



#if (FMM_PRECISION==0)
static int ida_allocate_dipole(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_t*)FMMV->DATA)->_0 = (_DATA_dipole_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_V0_t)); 
	if (!((DATA_dipole_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_dipole(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_t*)FMMV->DATA)->_0 = (_DATA_dipole_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_V0_t)); 
	if (!((DATA_dipole_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_t));
}


#endif /* FMM_PRECISION */



#if (FMM_PRECISION==0)
static int ida_allocate_grad(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_grad_t));
	if (!FMMV->DATA) goto _err;
	((DATA_grad_t*)FMMV->DATA)->_0 = (_DATA_grad_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_grad_V0_t)); 
	if (!((DATA_grad_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_grad(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_grad_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_grad_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_grad_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_grad(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_grad_t));
	if (!FMMV->DATA) goto _err;
	((DATA_grad_t*)FMMV->DATA)->_0 = (_DATA_grad_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_grad_V0_t)); 
	if (!((DATA_grad_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_grad(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_grad_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_grad_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_grad_t));
}


#endif /* FMM_PRECISION */



#if (FMM_PRECISION==0)
static int ida_allocate_dipole_grad(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_grad_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_grad_t*)FMMV->DATA)->_0 = (_DATA_dipole_grad_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_grad_V0_t)); 
	if (!((DATA_dipole_grad_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole_grad(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_grad_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_grad_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_grad_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_dipole_grad(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_grad_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_grad_t*)FMMV->DATA)->_0 = (_DATA_dipole_grad_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_grad_V0_t)); 
	if (!((DATA_dipole_grad_t*)FMMV->DATA)->_0) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole_grad(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_grad_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_grad_V0_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_grad_t));
}


#endif /* FMM_PRECISION */



#if (FMM_PRECISION==0)
static int ida_allocate_standard_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_standard_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_standard_ST_t*)FMMV->DATA)->_0 = (_DATA_standard_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_standard_ST_V0_t)); 
	if (!((DATA_standard_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_standard_ST_t*)FMMV->DATA)->_1 = (_DATA_standard_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_standard_ST_V1_t)); 
	if (!((DATA_standard_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_standard_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_standard_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_standard_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_standard_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_standard_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_standard_ST_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_standard_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_standard_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_standard_ST_t*)FMMV->DATA)->_0 = (_DATA_standard_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_standard_ST_V0_t)); 
	if (!((DATA_standard_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_standard_ST_t*)FMMV->DATA)->_1 = (_DATA_standard_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_standard_ST_V1_t)); 
	if (!((DATA_standard_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_standard_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_standard_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_standard_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_standard_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_standard_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_standard_ST_t));
}


#endif /* FMM_PRECISION */



#if (FMM_PRECISION==0)
static int ida_allocate_dipole_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_ST_t*)FMMV->DATA)->_0 = (_DATA_dipole_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_ST_V0_t)); 
	if (!((DATA_dipole_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_dipole_ST_t*)FMMV->DATA)->_1 = (_DATA_dipole_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_dipole_ST_V1_t)); 
	if (!((DATA_dipole_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_dipole_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_dipole_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_ST_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_dipole_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_ST_t*)FMMV->DATA)->_0 = (_DATA_dipole_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_ST_V0_t)); 
	if (!((DATA_dipole_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_dipole_ST_t*)FMMV->DATA)->_1 = (_DATA_dipole_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_dipole_ST_V1_t)); 
	if (!((DATA_dipole_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_dipole_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_dipole_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_ST_t));
}


#endif /* FMM_PRECISION */



#if (FMM_PRECISION==0)
static int ida_allocate_grad_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_grad_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_grad_ST_t*)FMMV->DATA)->_0 = (_DATA_grad_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_grad_ST_V0_t)); 
	if (!((DATA_grad_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_grad_ST_t*)FMMV->DATA)->_1 = (_DATA_grad_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_grad_ST_V1_t)); 
	if (!((DATA_grad_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_grad_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_grad_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_grad_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_grad_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_grad_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_grad_ST_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_grad_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_grad_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_grad_ST_t*)FMMV->DATA)->_0 = (_DATA_grad_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_grad_ST_V0_t)); 
	if (!((DATA_grad_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_grad_ST_t*)FMMV->DATA)->_1 = (_DATA_grad_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_grad_ST_V1_t)); 
	if (!((DATA_grad_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_grad_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_grad_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_grad_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_grad_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_grad_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_grad_ST_t));
}


#endif /* FMM_PRECISION */



#if (FMM_PRECISION==0)
static int ida_allocate_dipole_grad_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_grad_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_grad_ST_t*)FMMV->DATA)->_0 = (_DATA_dipole_grad_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_grad_ST_V0_t)); 
	if (!((DATA_dipole_grad_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_dipole_grad_ST_t*)FMMV->DATA)->_1 = (_DATA_dipole_grad_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_dipole_grad_ST_V1_t)); 
	if (!((DATA_dipole_grad_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole_grad_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_grad_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_grad_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_dipole_grad_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_dipole_grad_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_grad_ST_t));
}


#elif (FMM_PRECISION==1)
static int ida_allocate_dipole_grad_ST(FmmvHandle *FMMV)
{

	FMMV->DATA = (void*) FMMV_MALLOC(FMMV, sizeof(DATA_dipole_grad_ST_t));
	if (!FMMV->DATA) goto _err;
	((DATA_dipole_grad_ST_t*)FMMV->DATA)->_0 = (_DATA_dipole_grad_ST_V0_t *) FMMV_MALLOC(FMMV, FMMV->NParticles*sizeof(_DATA_dipole_grad_ST_V0_t)); 
	if (!((DATA_dipole_grad_ST_t*)FMMV->DATA)->_0) goto _err;
	((DATA_dipole_grad_ST_t*)FMMV->DATA)->_1 = (_DATA_dipole_grad_ST_V1_t *) FMMV_MALLOC(FMMV, FMMV->NTargets*sizeof(_DATA_dipole_grad_ST_V1_t)); 
	if (!((DATA_dipole_grad_ST_t*)FMMV->DATA)->_1) goto _err;

	return 0;

_err:
	return 1;
}

static void ida_free_dipole_grad_ST(FmmvHandle *FMMV)
{
	FMMV_FREE(FMMV, ((DATA_dipole_grad_ST_t*)FMMV->DATA)->_0, FMMV->NParticles*sizeof(_DATA_dipole_grad_ST_V0_t)); 
	FMMV_FREE(FMMV, ((DATA_dipole_grad_ST_t*)FMMV->DATA)->_1, FMMV->NTargets*sizeof(_DATA_dipole_grad_ST_V1_t)); 
	FMMV_FREE(FMMV, FMMV->DATA, sizeof(DATA_dipole_grad_ST_t));
}


#endif /* FMM_PRECISION */



int ida_allocate(FmmvHandle *FMMV)
{
	switch(FMMV->dataKind) {
	case FMM_STANDARD:
		return ida_allocate_standard(FMMV);
	case FMM_DIPOLE:
		return ida_allocate_dipole(FMMV);
	case FMM_GRAD:
		return ida_allocate_grad(FMMV);
	case FMM_DIPOLE_GRAD:
		return ida_allocate_dipole_grad(FMMV);
	case FMM_ST_STANDARD:
		return ida_allocate_standard_ST(FMMV);
	case FMM_ST_DIPOLE:
		return ida_allocate_dipole_ST(FMMV);
	case FMM_ST_GRAD:
		return ida_allocate_grad_ST(FMMV);
	case FMM_ST_DIPOLE_GRAD:
		return ida_allocate_dipole_grad_ST(FMMV);
	}
	return -1;
}

void ida_free(FmmvHandle *FMMV)
{
	switch(FMMV->dataKind) {
	case FMM_STANDARD:
		ida_free_standard(FMMV);
		break;
	case FMM_DIPOLE:
		ida_free_dipole(FMMV);
		break;
	case FMM_GRAD:
		ida_free_grad(FMMV);
		break;
	case FMM_DIPOLE_GRAD:
		ida_free_dipole_grad(FMMV);
		break;
	case FMM_ST_STANDARD:
		ida_free_standard_ST(FMMV);
		break;
	case FMM_ST_DIPOLE:
		ida_free_dipole_ST(FMMV);
		break;
	case FMM_ST_GRAD:
		ida_free_grad_ST(FMMV);
		break;
	case FMM_ST_DIPOLE_GRAD:
		ida_free_dipole_grad_ST(FMMV);
		break;
	}
}
